services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 10
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq 
      RABBITMQ_DEFAULT_PASS: rabbitmq

  migrate:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app/backend
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/postgres
    entrypoint: ["goose", "-dir", "migrations", "postgres", "postgres://postgres:secret@db:5432/postgres", "up"]

volumes:
  pgdata-dev:
