[request_definition]
r = obj, sub, act

[policy_definition]
p = obj, sub, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = keyMatch2(r.obj, p.obj) && (p.sub == "*" || r.sub == p.sub) && (p.act == "*" || r.act == p.act)
