/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HomepageRouteImport } from './routes/_homepage'
import { Route as HomepageIndexRouteImport } from './routes/_homepage/index'
import { Route as HomepageProjectRouteImport } from './routes/_homepage/project'
import { Route as HomepageProjectIdRouteImport } from './routes/_homepage/project/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/_homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageIndexRoute = HomepageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageProjectRoute = HomepageProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => HomepageRoute,
} as any)
const HomepageProjectIdRoute = HomepageProjectIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HomepageProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/project': typeof HomepageProjectRouteWithChildren
  '/': typeof HomepageIndexRoute
  '/project/$id': typeof HomepageProjectIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/project': typeof HomepageProjectRouteWithChildren
  '/': typeof HomepageIndexRoute
  '/project/$id': typeof HomepageProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_homepage': typeof HomepageRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_homepage/project': typeof HomepageProjectRouteWithChildren
  '/_homepage/': typeof HomepageIndexRoute
  '/_homepage/project/$id': typeof HomepageProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/login' | '/project' | '/' | '/project/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/login' | '/project' | '/' | '/project/$id'
  id:
    | '__root__'
    | '/_homepage'
    | '/about'
    | '/login'
    | '/_homepage/project'
    | '/_homepage/'
    | '/_homepage/project/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomepageRoute: typeof HomepageRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homepage': {
      id: '/_homepage'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_homepage/': {
      id: '/_homepage/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomepageIndexRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/project': {
      id: '/_homepage/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof HomepageProjectRouteImport
      parentRoute: typeof HomepageRoute
    }
    '/_homepage/project/$id': {
      id: '/_homepage/project/$id'
      path: '/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof HomepageProjectIdRouteImport
      parentRoute: typeof HomepageProjectRoute
    }
  }
}

interface HomepageProjectRouteChildren {
  HomepageProjectIdRoute: typeof HomepageProjectIdRoute
}

const HomepageProjectRouteChildren: HomepageProjectRouteChildren = {
  HomepageProjectIdRoute: HomepageProjectIdRoute,
}

const HomepageProjectRouteWithChildren = HomepageProjectRoute._addFileChildren(
  HomepageProjectRouteChildren,
)

interface HomepageRouteChildren {
  HomepageProjectRoute: typeof HomepageProjectRouteWithChildren
  HomepageIndexRoute: typeof HomepageIndexRoute
}

const HomepageRouteChildren: HomepageRouteChildren = {
  HomepageProjectRoute: HomepageProjectRouteWithChildren,
  HomepageIndexRoute: HomepageIndexRoute,
}

const HomepageRouteWithChildren = HomepageRoute._addFileChildren(
  HomepageRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomepageRoute: HomepageRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
